[package]
name = "calculator-ui"
version = "0.1.0"
edition = "2021"
description = "Template for starting a Yew project using Trunk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version="0.21", features=["csr"] }
